# Generated by Django 4.2.16 on 2026-01-07 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_procedurestepscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurestepscore',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprocedure',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprocedure',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_procedures', to=settings.AUTH_USER_MODEL),
        ),
    ]
