# Generated by Django 4.2.16 on 2026-01-08 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0005_procedurestepscore_is_reconciled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciledScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('reconciled_at', models.DateTimeField(auto_now=True)),
                ('reconciled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_reconciled', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.procedurestep')),
                ('student_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciled_scores', to='exams.studentprocedure')),
            ],
            options={
                'ordering': ['step__step_order'],
                'unique_together': {('student_procedure', 'step')},
            },
        ),
    ]
