# Generated by Django 4.2.16 on 2026-01-08 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0006_reconciledscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['level', 'index_number']},
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('100', 'Level 100'), ('200', 'Level 200'), ('300', 'Level 300'), ('400', 'Level 400')], default='100', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='procedurestepscore',
            unique_together={('student_procedure', 'step', 'examiner', 'is_reconciled')},
        ),
    ]
