# Generated by Django 4.2.16 on 2026-01-13 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0007_alter_student_options_student_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveIntegerField(default=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plan_assessments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='exams.student')),
            ],
            options={
                'ordering': ['-assessed_at'],
                'unique_together': {('student', 'program')},
            },
        ),
    ]
