# Generated by Django 4.2.16 on 2026-01-22 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0008_careplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprocedure',
            name='assigned_reconciler',
            field=models.ForeignKey(blank=True, help_text='The examiner assigned to perform reconciliation (locked once set)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
    ]
